### ISSUE TITLE
Resize above t3a.large

### ISSUE THREAD

**Issue by sn0rlacks** [aws-samples/personal-game-server-manager#1]
I deployed as t3a.large but need xlarge or above, however the webui doesn't show value higher than t3a.large.

I notice in code that references to xl and 2xl are made so I'm curious how I can size up and maintain map progress?

**Comment by drsp123isen** [comment]
The front end just refers to micro, small, medium and large - these are mapped to actual EC2 instances in Lambda environment variables so you can change (for example) what a large is to any supported x86 EC2 instance.  To do this, login to the AWS console (https://console.aws.amazon.com/console/home) and go the Lambda service.  Within the Lambda service page, go to Functions and select the one that has "mcStartStopLambda" in the middle of the name.  Then go to Configuration --> Environment Variables, on that screen you should see what EC2 instance each size on the front end is mapped to.  Just change the value to whatever EC2 instance you want, for example you could change the "t3a.large" value to "t3a.2xlarge" or even "m6a.48xlarge" if you wanted to really go big....
